### ISSUE TITLE
libcopra.so.1: undefined symbol: _ZN5Eigen3QLD7problemEii

### ISSUE THREAD

**Issue by ayuguchi** [vsamy/copra#10]
Hello, 
thank you for providing your warmful humanoid packages :)
Now,  I am trying to use your packages especially `lipm_walking_controller`.

After installed required dependencies and then I launch rviz and choreonoid following the usage of the README, I have faced this below error when I started clicking `start walking` by the rviz GUI.
```
choreonoid: symbol lookup error: /usr/lib/x86_64-linux-gnu/libcopra.so.1: undefined symbol: _ZN5Eigen3QLD7problemEii
```
About copra, I installed `libcopra-dev`. Could you have any advice to solve it?

**Comment by vsamy** [comment]
This issue should be ask to `lipm_walking_controller`. 
But basically it means that the version `libcopra-dev` is an old version.
The issue is quite old, so I think this is already fix.
