### ISSUE TITLE
Compile options not properly set

### ISSUE THREAD

**Issue by stephane-caron** [vsamy/copra#2]
I use Copra in a CMake project by:
```
add_required_dependency(copra)
pkg_config_use_dependency(${PROJECT_NAME} copra)
```
Compile options are defined in Copra's CMakeLists.txt by:
```
if(${EIGEN_QLD_FOUND})
    add_compile_options(-DEIGEN_QLD_FOUND)
endif()
```
However, this block is only valid to compile Copra and my project does not see it. For instance if I want to use QLD, for now I manually add the above compile options to my CMakeLists.txt, otherwise compilation fails with the following error:
```
error: ‘QLD’ is not a member of ‘copra::SolverFlag’
     copra::LMPC lmpc(previewSystem_, copra::SolverFlag::QLD);
```
This problem did not appear previously when ``solverConfig.cmake.in`` was used.

**Comment by stephane-caron** [comment]
Just tried with the latest ``master`` branch of copra and the problem is still around:
```
.../ModelPredictiveControl.h:319:33: error: ‘QLD’ is not a member of ‘copra::SolverFlag’
     copra::SolverFlag solver_ = copra::SolverFlag::QLD;
```
If I add the following two lines to my main CMakeLists.txt the error goes away:
```
add_compile_options(-DEIGEN_QLD_FOUND) # see https://github.com/vsamy/copra/issues/2
add_compile_options(-DEIGEN_LSSOL_FOUND) # see https://github.com/vsamy/copra/issues/2
```
My controller is compiled via catkin. How is it supposed to see that it needs to add these flags?

**Comment by stephane-caron** [comment]
Ah right, it goes through pkgconfig, which is found in my controller's [CMakeLists.txt](https://github.com/stephane-caron/lipm_walking_controller/blob/master/src/CMakeLists.txt) via this instruction:
```
pkg_config_use_dependency(${PROJECT_NAME} copra)
```
The compilation flag is indeed written in my system-wide copra.pc:
```
tail /usr/local/lib/pkgconfig/copra.pc -n3
Cflags:  -I${includedir} -DEIGEN_LSSOL_FOUND -DEIGEN_QLD_FOUND
```
Yet, these compilation flags are not used by catkin. Here is the compilation line that fails according to ``catkin_make -DCMAKE_VERBOSE_MAKEFILE=ON``:
```bash
cd /home/scaron/Software/catkin_ws/build/lipm_walking_controller/src && /usr/bin/c++  -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"lipm_walking_controller\" -Dlipm_walking_controller_controller_EXPORTS -I/home/scaron/Software/catkin_ws/src/lipm_walking_controller/include -I/opt/ros/indigo/include -I/home/scaron/.local/include -isystem /usr/local/include/eigen3  -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion -O2 -g -DNDEBUG -fPIC   -std=c++14 -o CMakeFiles/lipm_walking_controller_controller.dir/lib.cpp.o -c /home/scaron/Software/catkin_ws/src/lipm_walking_controller/src/lib.cpp
```
The package is [lipm_walking_controller](https://github.com/stephane-caron/lipm_walking_controller/).

**Comment by vsamy** [comment]
I am investigating this, but i feel like it is a problem between `jrl-cmake-module` and `catkin`. 
I do not know what `catkin` really do.

I asked the question to `jrl-cmake-module`. 
First, make sure you don't have a second `copra.pc` that could break everything.

**Comment by stephane-caron** [comment]
Solved by 22c9dfce60ab5c0017abf7f83fd992c34665cfe7 after updating the CMakeLists of my project accordingly https://github.com/stephane-caron/lipm_walking_controller/commit/dea206f4a438a7dc216424c9655576c540035e5b. Thanks!

**Comment by kurt** [comment]
I had a similar problem and the essence was the add_target_libraries().... the header I was trying to include needed to be also be linked properly by cmake in compilation

**Comment by gergondet** [comment]
hi @kurt 

The current correct way to consume copra in CMake is to do:
```
find_package(copra REQUIRED)
target_link_libraries(YourExecutableOrLibrary PUBLIC copra::copra)
```

**Comment by kurt** [comment]
Thanks @gergondet!
