### ISSUE TITLE
compile for C++11.

### ISSUE THREAD

**Issue by QingweiLau** [vsamy/copra#3]
hi could I still compile with c++11 since I can not find the  c++11-back-compatibility branch?

**Comment by vsamy** [comment]
Sorry, it won't compile with a c++11 compiler. I deleted the c++11-back-compatibility branch because it was very cumbersome to maintain 2 branches in parallel. Feel free to make the necessary changes to write a c++11 compilable version.

**Comment by vsamy** [comment]
I modify the Readme and deleted the reference to the c++11-back-compatibility branch.
