### ISSUE TITLE
cmake problem with python binding

### ISSUE THREAD

**Issue by ghost** [vsamy/copra#6]
Hi. I am getting this error when I want to use cmake when I add python for binding and using pyCopra to my CMakeList.txt and I don't know how to solve it. Would you please help me for solving this problem?

Thank You
```

-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- The CXX compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test R-pedantic
-- Performing Test R-pedantic - Success
-- Performing Test R-Wno-long-long
-- Performing Test R-Wno-long-long - Success
-- Performing Test R-Wall
-- Performing Test R-Wall - Success
-- Performing Test R-Wextra
-- Performing Test R-Wextra - Success
-- Performing Test R-Wcast-align
-- Performing Test R-Wcast-align - Success
-- Performing Test R-Wcast-qual
-- Performing Test R-Wcast-qual - Success
-- Performing Test R-Wformat
-- Performing Test R-Wformat - Success
-- Performing Test R-Wwrite-strings
-- Performing Test R-Wwrite-strings - Success
-- Performing Test R-Wconversion
-- Performing Test R-Wconversion - Success
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   unit_test_framework
CMake Error at binding/python/CMakeLists.txt:22 (find_package):
  By not providing "FindPython.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Python", but
  CMake did not find one.

  Could not find a package configuration file provided by "Python" with any
  of the following names:

    PythonConfig.cmake
    python-config.cmake

  Add the installation prefix of "Python" to CMAKE_PREFIX_PATH or set
  "Python_DIR" to a directory containing one of the above files.  If "Python"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/mohammad/catkin_ws/lipm/copra/build/CMakeFiles/CMakeOutput.log".

```

**Comment by vsamy** [comment]
Hi, 

Thank you for using copra.

Ok, I think I forgot to update the `cmake_minimum_package` requierement. Is your cmake `version < 3.12.4`. If so, please upgrade your cmake and try again.

**Comment by ghost** [comment]
Thank you for your reply. That problem is solved. By I still get the following error. Do you have any idea how to fix it?
P.S: I think I have numpy

Thank You
```

-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- The CXX compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at cmake/base.cmake:198 (PROJECT):
  DESCRIPTION keyword not followed by a value or was followed by a value that
  expanded to nothing.
Call Stack (most recent call first):
  CMakeLists.txt:38 (setup_project)


-- Performing Test R-pedantic
-- Performing Test R-pedantic - Success
-- Performing Test R-Wno-long-long
-- Performing Test R-Wno-long-long - Success
-- Performing Test R-Wall
-- Performing Test R-Wall - Success
-- Performing Test R-Wextra
-- Performing Test R-Wextra - Success
-- Performing Test R-Wcast-align
-- Performing Test R-Wcast-align - Success
-- Performing Test R-Wcast-qual
-- Performing Test R-Wcast-qual - Success
-- Performing Test R-Wformat
-- Performing Test R-Wformat - Success
-- Performing Test R-Wwrite-strings
-- Performing Test R-Wwrite-strings - Success
-- Performing Test R-Wconversion
-- Performing Test R-Wconversion - Success
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") found components: doxygen dot 
-- Found Boost: /usr/include (found version "1.58.0") found components: unit_test_framework 
-- Found Python: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found version "3.5") found components: Development 
CMake Error at /usr/local/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Boost (missing: numpy) (found version "1.58.0")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.16/Modules/FindBoost.cmake:2162 (find_package_handle_standard_args)
  binding/python/CMakeLists.txt:23 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/mohammad/catkin_ws/lipm/copra/build/CMakeFiles/CMakeOutput.log".

```

**Comment by vsamy** [comment]
Sorry for the late answer.

Python bindings need Boost python and Boost numpy
You need to install these on your system.

**Comment by LeoHe158** [comment]
Hi, 
Please How to solve the problem of "Could not find a package configuration file provided by "Python" with any
  of the following names: ......".
I'm Looking forward to your reply.
Thanks

**Comment by gergondet** [comment]
Hi @LeoHe158 

Which version of CMake are you using? As suggested by @vsamy you need at least CMake 3.12.4 or later

You will also need Boost and in particular the Boost Python package for the bindings to build

**Comment by LeoHe158** [comment]
Hi&nbsp;jrl-umi3218/copra



Thank you for your reply.

My CMake version is 3.19.7

I'll try as you suggest.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jrl-umi3218/copra"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月20日(星期一) 下午2:38
***@***.***&gt;;
抄送:&nbsp;"Leo ***@***.******@***.***&gt;;
主题:&nbsp;Re: [jrl-umi3218/copra] cmake problem with python binding (#6)





 
Hi @LeoHe158
 
Which version of CMake are you using? As suggested by @vsamy you need at least CMake 3.12.4 or later
 
You will also need Boost and in particular the Boost Python package for the bindings to build
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gergondet** [comment]
Hi,

Then this version should be ok. Which system are you using?

**Comment by LeoHe158** [comment]
Hi,

Thank you for your reply.

My system is Fedora release 33







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jrl-umi3218/copra"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月20日(星期一) 下午3:12
***@***.***&gt;;
抄送:&nbsp;"Leo ***@***.******@***.***&gt;;
主题:&nbsp;Re: [jrl-umi3218/copra] cmake problem with python binding (#6)





 
Hi,
 
Then this version should be ok. Which system are you using?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
