### ISSUE TITLE
Cost for a single iteration/step

### ISSUE THREAD

**Issue by ndehio** [vsamy/copra#9]
Hi
I want to implement a control-cost that is evaluated only once (in the first iteration).
My idea was to use a vector of weights which are all zero except for the first one.
However, for some reason the following does not work... the simulation seems to stop/hang when calling weights() method.
```
uCost = std::make_shared<copra::ControlCost>(uCostMat, uCostVec);
// uCost->weight(0.5); //single weight for all iterations/steps, works for me
Eigen::VectorXd uWeights;
uWeights = Eigen::VectorXd::Zero(nbSteps); //nbSteps is identical to the horizon of the preview system
uWeights(0) = 0.5;
uCost->weights(uWeights); //individual weight for each iteration/step ??
```
What am I doing wrong here?

Do I also need to call the autoSpan() function?

**Comment by vsamy** [comment]
Thanks for using copra.

The weight vector should be of the same size as your `uCostVect`. 
The Reason behind this is that if you design all your cost and constraint as constant through the horizon of time, the Library can use some optimization  and memory saving while solving.

Note that `uCost->weight(0.5);` performs a bit differently. It fills the the weight vector with the given value. So, for a dimension-3 weight vector, it becomes `[0.5, 0.5, 0.5]`.

If you need the weight vector to vary through the horizon of time, you first need to call the `autoSpan()` function of the cost class. This will generate a weigh vector of size `nbSteps * weights.size()`. Then, you can set the weight vector directly.

You said that your program hangs. I am a bit curious to see that. The program should throw an error when setting a bad dimension. Could you tell me the dimension of `uCostVec` and `nbSteps` that generated a hang?

Thank you
